# Generated by Django 5.0.4 on 2024-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoevents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/events/'),
        ),
        migrations.AlterField(
            model_name='photoevents',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/events/'),
        ),
    ]
